const $=s=>document.querySelector(s);let expenses=JSON.parse(localStorage.getItem('gastosEmpresa')||'[]'), imgData='';
const euro=n=>Number(n||0).toLocaleString('es-ES',{style:'currency',currency:'EUR'}); const num=s=>Number(String(s||'').replace(/\s/g,'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''))||0;
function persist(){localStorage.setItem('gastosEmpresa',JSON.stringify(expenses));render()}
function render(){let box=$('#list');box.innerHTML=expenses.length?'':'<p class="muted">Aún no hay gastos.</p>';expenses.forEach((e,i)=>{let d=document.createElement('div');d.className='expense';d.innerHTML=`<div><b>${e.merchant||'Sin comercio'}</b><div class="muted">${e.date||'Sin fecha'} · ${e.category} · ${e.cost||'Sin centro de coste'}</div></div><div><b>${euro(e.amount)}</b><br><button class="danger" data-i="${i}">Eliminar</button></div>`;box.appendChild(d)});$('#total').textContent=euro(expenses.reduce((a,e)=>a+e.amount,0));document.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>{expenses.splice(+b.dataset.i,1);persist()})}
function extract(text){let lines=text.split(/\n/).map(x=>x.trim()).filter(Boolean);$('#merchant').value=lines.find(x=>/[A-Za-zÁÉÍÓÚÑáéíóúñ]{3}/.test(x))||'';let ds=text.match(/\b(\d{1,2})[\/.-](\d{1,2})[\/.-](\d{2,4})\b/);if(ds){let y=ds[3].length===2?'20'+ds[3]:ds[3];$('#date').value=`${y}-${ds[2].padStart(2,'0')}-${ds[1].padStart(2,'0')}`};let totals=[...text.matchAll(/(?:TOTAL|IMPORTE|A PAGAR)[^0-9]{0,15}(\d+[.,]\d{2})/gi)].map(m=>num(m[1]));let all=[...text.matchAll(/\b(\d+[.,]\d{2})\s*(?:€|EUR)?/gi)].map(m=>num(m[1]));$('#amount').value=(totals.at(-1)||Math.max(0,...all)||'').toString().replace('.',',');let iva=text.match(/(?:IVA|I\.V\.A\.)[^0-9]{0,15}(\d+[.,]\d{2})/i);if(iva)$('#tax').value=iva[1]}
$('#photo').onchange=async e=>{let f=e.target.files[0];if(!f)return;imgData=await new Promise(r=>{let fr=new FileReader;fr.onload=()=>r(fr.result);fr.readAsDataURL(f)});$('#preview').src=imgData;$('#preview').hidden=false;$('#prog').hidden=false;$('#status').textContent='Leyendo ticket…';try{let r=await Tesseract.recognize(f,'spa',{logger:m=>{if(m.progress)$('#prog i').style.width=(m.progress*100)+'%'}});extract(r.data.text);$('#status').textContent='Lectura terminada. Comprueba fecha, comercio e importe.'}catch(err){$('#status').textContent='No se pudo ejecutar el OCR. Puedes completar los campos manualmente.'}};
$('#save').onclick=()=>{if(!imgData)return alert('Añade una foto del ticket.');if(!num($('#amount').value))return alert('Indica un importe válido.');expenses.unshift({id:crypto.randomUUID(),date:$('#date').value,merchant:$('#merchant').value.trim(),amount:num($('#amount').value),tax:num($('#tax').value),category:$('#category').value,cost:$('#cost').value.trim(),notes:$('#notes').value.trim(),image:imgData});persist();clearForm()};
function clearForm(){['date','merchant','amount','tax','cost','notes'].forEach(id=>$('#'+id).value='');imgData='';$('#photo').value='';$('#preview').hidden=true;$('#prog').hidden=true;$('#prog i').style.width='0'}$('#clear').onclick=clearForm;
function csvBlob(){let rows=[['Fecha','Comercio','Importe','IVA','Categoría','Centro de coste','Comentario'],...expenses.map(e=>[e.date,e.merchant,e.amount,e.tax,e.category,e.cost,e.notes])];let t='\ufeff'+rows.map(r=>r.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n');return new Blob([t],{type:'text/csv;charset=utf-8'})}function dl(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
$('#csv').onclick=()=>dl(csvBlob(),'gastos_empresa.csv');$('#backup').onclick=()=>dl(new Blob([JSON.stringify(expenses,null,2)],{type:'application/json'}),'gastos_empresa.json');$('#all').onclick=()=>{if(confirm('¿Borrar todos los gastos guardados en este dispositivo?')){expenses=[];persist()}};
$('#share').onclick=async()=>{if(!expenses.length)return alert('No hay gastos para enviar.');let files=[new File([csvBlob()],'gastos_empresa.csv',{type:'text/csv'})];for(let i=0;i<expenses.length;i++){let b=await fetch(expenses[i].image).then(r=>r.blob());files.push(new File([b],`ticket_${i+1}_${expenses[i].date||'sin_fecha'}.${b.type.includes('png')?'png':'jpg'}`,{type:b.type}))}let total=euro(expenses.reduce((a,e)=>a+e.amount,0));let text=`Buenos días,\n\nAdjunto la relación de gastos de tarjeta de empresa y sus justificantes.\n\nTotal: ${total}\n\nUn saludo.`;if(navigator.canShare&&navigator.canShare({files})){await navigator.share({title:'Gastos tarjeta de empresa',text,files})}else{dl(csvBlob(),'gastos_empresa.csv');files.slice(1).forEach(f=>dl(f,f.name));location.href=`mailto:?subject=${encodeURIComponent('Gastos tarjeta de empresa')}&body=${encodeURIComponent(text+'\n\nLos archivos se han descargado para adjuntarlos al correo.')}`}};render();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');